INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'ESTADÍSTICA PARA INGENIERÍA',	'EST218',1);
INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'ELECTRÓNICA DIGITAL',	'IEE229',1);
INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'BASES DE DATOS',	'INF246',1);
INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'ESTRUCTURA DE DATOS Y PROGRAMACIÓN METÓDICA',	'1INF06',1);
INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'ORGANIZACIÓN Y ARQUITECTURA DE COMPUTADORAS',	'IEE240',1);
INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'SISTEMAS DE INFORMACIÓN', 1	'INF248',1);
INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'LENGUAJE DE PROGRAMACIÓN', 1	'INF281',1);
INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'MÉTODOS Y PROCEDIMIENTOS',	'INF291',1);
INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'PRÁCTICA SUPERVISADA PREPROFESIONAL',	'INF008',1);
INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'SISTEMAS OPERATIVOS',	'INF239',1);
INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'SISTEMAS DE INFORMACIÓN 2',	'INF250',1);
INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'APLICACIONES DE CIENCIAS DE LA COMPUTACIÓN',	'INF265',1);
INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'LENGUAJE DE PROGRAMACIÓN 2',	'INF282',1);
INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'TEORÍA DE COMUNICACIONES',	'TEL201',1);
INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'REDES DE COMPUTADORAS',	'INF238',1);
INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'INGENIERÍA DE SOFTWARE','INF245',1);
INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'EXPERIMENTACIÓN NUMÉRICA',	'1INF07',1);
INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'DESARROLLO DE PROGRAMAS 1', 	'INF226',1);
INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'MODELOS Y SIMULACIÓN EMPRESARIAL',	'INF234',1);
INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'ADMINISTRACIÓN DE LA FUNCIÓN INFORMÁTICA',	'INF273',1);
INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'ADMINISTRACIÓN DE SISTEMAS OPERATIVOS Y BASE DE DATOS',	'INF274',1);
INSERT INTO CURSOS (ID_ESPECIALIDAD,ID_SEMESTRE,NOMBRE,CODIGO_CURSO,ESTADO) VALUES(
	1,1,'PLANEAMIENTO ESTRATÉGICO EN INFORMÁTICA',	'INF295',1);
